### ISSUE TITLE
Add tool to export GH issues as a task file

### ISSUE THREAD

**Issue by chmp** [chmp/tools#12]
Workflow idea:

- generate md file
- include md file in mdban

See for example: https://api.github.com/repos/chmp/tools/issues

Use labels to select columns. Idea:

```toml
[[external.tools]]
type = "github"
repo = "chmp/tools"

default_column = "Todo"
columns = { Backlog = ["backlog"] }
```
